### ISSUE TITLE
Consider using an existing rust validation library?

### ISSUE THREAD

**Issue by jmetz** [kreshuklab/bioimg_rs#2]
When looking into the feasibility of this recently, I came across eg 

* `validator` - https://crates.io/crates/validator
*  `garde` - https://crates.io/crates/garde
* `serde_valid` - https://crates.io/crates/serde_valid 

Perhaps it would make more sense to use one of these for the "easy" fields and only worry about the more complicated validation logic ourselves - or is there a reason not to?

**Comment by Tomaz-Vieira** [comment]
So I looked into the libraries and if I understand correctly, the flow is something like this:

```rust
pub struct User{
  #[validate(minimum = 0)]
  #[validate(maximum = 120)] // users can be at most 120 years old
  age: u8,
}

let user = User{age: 255}; // instantiate an invalid user
if let Err(err) = user.validate(){
  # handle invalid value
}
```

It's nice that we don't have to write the validation code ourselves, but it does come at a cost: Because this validation is **not done at construction-time**, it is possible to have invalid `User`s floating around the code, meaning that any code that touches a `User` can't be sure that it's dealing with a valid `User`, and that limits the compiler's ability to catch errors; the compiler can never enforce that we are actually calling `.validate()` and then handling the errors accordingly.

Still, what we have today might not be too different from that... Under `bioimg_spec::rdf` we have the stuff  that is serialized directly to YAML, and under `bioimg_spec::runtime` we have structs that are parsed, "valid" objects, constructed from those in `bioimg_spec::rdf`. So, the `rdf::*` stuff is like "syntactic" checking and the `runtime::*` stuff is like "semantic" validation. So it's conceivable we could use those validation libraries inside `runtime::*`, though I don't if it will actually make our lives easier than to simply write the validation code :thinking: 

I'll come back to this one `runtime::*` is more populated so I can have a feel of how annoying the validation code is actually getting.

**Comment by jmetz** [comment]
Hmm I guess this is almost always going to be used for runtime validation - that's kinda the point of the library. 

The idea of enforcing compile-time validation, for the rare scenario where someone is hard-coding an RDF in rust... I'm not sure it made sense to spend time on that tbh :shrug: 

That said, you've done that now I guess.  I'm still not 100% clear as to the utility... am testing now.

**Comment by jmetz** [comment]
I just tested your argument, and it does not really work as you had intentioned - see #3
